#log
logging:
  config: classpath:logback.xml

#开发环境
breakpoint:
  upload:
    # 文件上传目录
    dir: D:/data0/uploads
    cache: 2
    #1024*1024=1 048 576,5M=5 242 880 单个块的大小
    chunkSize: 5 242 880
  download:
    port: 8080
spring:
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 100MB
  # redis 的配置
  redis:
    host: 127.0.0.1
    port: 6379
    password:
    timeout: 2S
    jedis:
      pool:
        max-active: 30
        max-idle: 10
        max-wait: 10000