CREATE TABLE `t_user` (
	`USER_ID` INT(11) NOT NULL AUTO_INCREMENT,
	`USER_NAME` VARCHAR(50) NOT NULL COMMENT '主数据库用户名',
	`USER_PASSWORD` VARCHAR(50) NOT NULL COMMENT '主数据库密码',
	`SEX` INT(4) NOT NULL COMMENT '用户性别',
	`AGE` INT(4) NOT NULL COMMENT '年龄',
	PRIMARY KEY (`USER_ID`)
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB
;
